
const PACKS_CANDY_MACHINE = 'CumKt2ndD5aGc1vkUkEt8inpxKF97prPQvgHMc6tVVoz';
const PACKS_COLLECTION = '8N83n6mxSFiFQXkj7zW4Qse4Mp5R7LmiLm3mTvbXDLiE';
const CARDS_COLLECTION = 'AhTNAsQCGC3BcLwNnsjq3ig77RxJTFtXAsGmN2yhwrUq';
const UPDATE_AUTHORITY = 'CshGnGs5aAsqcUxqu58QtrsBAU8RAzstA45ygjooXsGD';

export { PACKS_CANDY_MACHINE, PACKS_COLLECTION, UPDATE_AUTHORITY, CARDS_COLLECTION };
